version: '3'
services:
  db:
    image: postgres:alpine
  mysite:
    build: .
    command: django-start.sh
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/app
    depends_on:
      - db
